services:
    app:
        image: noeldemartin/proxy
        volumes:
            - ./storage:/app/storage
            - ./.env:/app/.env
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - proxy

networks:
    default:
        name: nginx-agora
        external: true
