#!/usr/bin/env bash

function proxy-docker-compose() {
    docker-compose -f $base_dir/docker-compose.prod.yml $@
}

function proxy-cli() {
    $base_dir/proxy $@
}

function proxy_is_running() {
    if [ -z $(proxy-docker-compose ps --quiet | head -n 1) ]; then
        false
    fi
}

function proxy_is_headless() {
    if [ -d "$base_dir/app" ]; then
        false
    fi
}

export base_dir=`cd $(readlink -f $0 | xargs dirname) && pwd`
export scripts_dir="$base_dir/scripts"
export -f proxy-docker-compose
export -f proxy-cli
export -f proxy_is_running
export -f proxy_is_headless

command=$1

case "$command" in
    'help' | '' )
        echo 'proxy install          | initialize app files'
        echo 'proxy start            | start app services'
        echo 'proxy restart          | restart app services'
        echo 'proxy stop             | stop app services'
        echo 'proxy update           | update app and restart'
        echo 'proxy chown            | set permissions for storage'
        echo 'proxy publish-assets   | publish assets into /public folder'
        echo 'proxy shell {service?} | open shell in a running container'
        echo 'proxy docker-compose   | run docker-compose command'
        ;;
    'stop' )
        proxy-docker-compose down
        ;;
    'restart' )
        proxy-cli stop
        proxy-cli start
        ;;
    'docker-compose' )
        proxy-docker-compose ${@:2}
        ;;
    'install' | 'start' | 'update' | 'chown' | 'publish-assets' | 'shell' )
        $scripts_dir/$command.sh ${@:2}
        ;;
    * )
        echo "Unknown command '$command'"
        ;;
esac
