name: DockerHub
on: [push]
jobs:

  # This publishes a development image, to tag an image to be used in production run the following
  # commands in your machine:
  # docker pull noeldemartin/proxy:{commit-id}
  # docker tag noeldemartin/proxy:{commit-id} noeldemartin/proxy:latest
  # docker push noeldemartin/proxy:latest

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Install Node dependencies
        run: npm ci --no-audit
      - name: Generate assets
        run: npm run prod
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/proxy:$(git rev-parse HEAD)
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/proxy:$(git rev-parse HEAD)
